### ISSUE TITLE
Running tests

### ISSUE THREAD

**Issue by rtodea** [spatialdev/PGRestAPI#119]
Can someone help me with running the `test` folder content?
I have made some modifications to the codebase and would like to run the existing tests.
I could not find any documentation for this.

**Comment by apollolm** [comment]
Hi - you should be able to run the tests by running

    node_modules/.bin/mocha -u tdd --reporter spec

(I took this from package.json).

The test folder is mostly a dump of CartoDB's test folder, and I planned on wiring up similar tests to PGRestAPI.  Unfortunately, I didn't get around to that, so only 3 test suites are being run:

common.js
tables.js
vector_tiles.js

These are also deficient tests since they depend on a known instance and are hard-coded to those values.  I started a branch of this project that involved some major refactoring and updates to the tests to remove the dependencies on a live instance of the API, but never finished.

**Comment by rtodea** [comment]
Thanks for the quick reply.

You say that these tests are "deficient". Is
```
  10 passing (202ms)
  12 failing
```
a statistic you expect?

The entire output for reference:
```
  ✓ escapePostGresColumns returns array
  ✓ escapePostGresColumns returns double quoted names
  ✓ unEscapePostGresColumns returns array
  ✓ unEscapePostGresColumns returns double quoted names
  ✓ GeoJSON Formatter - valid GeoJSON passes validation
  ✓ GeoJSON Formatter - Invalid GeoJSON fails validation
  ✓ common.GetArguments returns arguments from POST requests

  Tables
    ✓ returns list of tables posts as an array
    1) Loads a specific table endoint
    2) Queries a specific table endoint with returnFields set to country, limit = 100
    3) Queries a specific table endoint to get geojson: whereClause is 1=1, returnFields set to country, limit 100
    4) Queries a specific table endoint to get geojson: whereClause is id<10, returnFields set to country
    5) Queries a specific table endoint to get geojson: whereClause is id<10, returnFields set to country, returnGeometry=no
    6) Queries a specific table endoint to get geojson: whereClause is id<10, returnFields set to country, returnGeometry=no, returnGeometryEnvelopes=yes
    ✓ Queries a specific table endoint to get geojson: group by with no statsdef
    7) Queries a specific table endoint to get geojson: whereClause is id<10, returnFields set to country, returnGeometry=no, group by country, statsdev = co                                                                                                                 unt:id,sum:number_employees limit=100
    8) Queries a specific table endoint to get geojson - using wkt intersect geom: whereClause is id<10, returnFields set to country, limit=100
    9) Queries a specific table endoint to get geojson:  Offset = 1000, returnFields set to country and id, limit=100
    10) Queries a specific table endoint as csv: whereClause is 1=1, returnFields set to country, limit 100
    11) Queries a specific table endoint as shapefile: whereClause is 1=1, returnFields set to country, limit 100

 Vector Tiles
    12) requests a dynamic .pbf tile from a PostGIS database

  10 passing (202ms)
  12 failing

  1) Tables Loads a specific table endoint:
     Uncaught AssertionError: expected { Object (error) } to have a property 'columns'
      at Test.<anonymous> (test/tables.js:45:32)
      at Test.assert (node_modules/supertest/lib/test.js:156:6)
      at assert (node_modules/supertest/lib/test.js:127:12)
      at node_modules/supertest/lib/test.js:124:5
      at Test.Request.callback (node_modules/supertest/node_modules/superagent/lib/node/index.js:785:12)
      at IncomingMessage.<anonymous> (node_modules/supertest/node_modules/superagent/lib/node/index.js:990:12)
      at _stream_readable.js:944:16

  2) Tables Queries a specific table endoint with returnFields set to country, limit = 100:
     Uncaught AssertionError: expected { Object (error) } to have a property 'features'
      at Test.<anonymous> (test/tables.js:56:32)
      at Test.assert (node_modules/supertest/lib/test.js:156:6)
      at assert (node_modules/supertest/lib/test.js:127:12)
      at node_modules/supertest/lib/test.js:124:5
      at Test.Request.callback (node_modules/supertest/node_modules/superagent/lib/node/index.js:785:12)
      at IncomingMessage.<anonymous> (node_modules/supertest/node_modules/superagent/lib/node/index.js:990:12)
      at _stream_readable.js:944:16

  3) Tables Queries a specific table endoint to get geojson: whereClause is 1=1, returnFields set to country, limit 100:
     Uncaught AssertionError: expected { Object (error) } to have a property 'features'
      at Test.<anonymous> (test/tables.js:69:32)
      at Test.assert (node_modules/supertest/lib/test.js:156:6)
      at assert (node_modules/supertest/lib/test.js:127:12)
      at node_modules/supertest/lib/test.js:124:5
      at Test.Request.callback (node_modules/supertest/node_modules/superagent/lib/node/index.js:785:12)
      at IncomingMessage.<anonymous> (node_modules/supertest/node_modules/superagent/lib/node/index.js:990:12)
      at _stream_readable.js:944:16

  4) Tables Queries a specific table endoint to get geojson: whereClause is id<10, returnFields set to country:
     Uncaught AssertionError: expected { Object (error) } to have a property 'features'
      at Test.<anonymous> (test/tables.js:84:32)
      at Test.assert (node_modules/supertest/lib/test.js:156:6)
      at assert (node_modules/supertest/lib/test.js:127:12)
      at node_modules/supertest/lib/test.js:124:5
      at Test.Request.callback (node_modules/supertest/node_modules/superagent/lib/node/index.js:785:12)
      at IncomingMessage.<anonymous> (node_modules/supertest/node_modules/superagent/lib/node/index.js:990:12)
      at _stream_readable.js:944:16

  5) Tables Queries a specific table endoint to get geojson: whereClause is id<10, returnFields set to country, returnGeometry=no:
     Uncaught AssertionError: expected { Object (error) } to have a property 'features'
      at Test.<anonymous> (test/tables.js:99:32)
      at Test.assert (node_modules/supertest/lib/test.js:156:6)
      at assert (node_modules/supertest/lib/test.js:127:12)
      at node_modules/supertest/lib/test.js:124:5
      at Test.Request.callback (node_modules/supertest/node_modules/superagent/lib/node/index.js:785:12)
      at IncomingMessage.<anonymous> (node_modules/supertest/node_modules/superagent/lib/node/index.js:990:12)

  6) Tables Queries a specific table endoint to get geojson: whereClause is id<10, returnFields set to country, returnGeometry=no, returnGeometryEnvelopes=ye                                                                                                                 s:
     Uncaught AssertionError: expected { Object (error) } to have a property 'features'
      at Test.<anonymous> (test/tables.js:114:32)
      at Test.assert (node_modules/supertest/lib/test.js:156:6)
      at assert (node_modules/supertest/lib/test.js:127:12)
      at node_modules/supertest/lib/test.js:124:5
      at Test.Request.callback (node_modules/supertest/node_modules/superagent/lib/node/index.js:785:12)
      at IncomingMessage.<anonymous> (node_modules/supertest/node_modules/superagent/lib/node/index.js:990:12)
      at _stream_readable.js:944:16

  7) Tables Queries a specific table endoint to get geojson: whereClause is id<10, returnFields set to country, returnGeometry=no, group by country, statsdev                                                                                                                  = count:id,sum:number_employees limit=100:
     Uncaught AssertionError: expected { Object (error) } to have a property 'features'
      at Test.<anonymous> (test/tables.js:141:32)
      at Test.assert (node_modules/supertest/lib/test.js:156:6)
      at assert (node_modules/supertest/lib/test.js:127:12)
      at node_modules/supertest/lib/test.js:124:5
      at Test.Request.callback (node_modules/supertest/node_modules/superagent/lib/node/index.js:785:12)
      at IncomingMessage.<anonymous> (node_modules/supertest/node_modules/superagent/lib/node/index.js:990:12)
      at _stream_readable.js:944:16

  8) Tables Queries a specific table endoint to get geojson - using wkt intersect geom: whereClause is id<10, returnFields set to country, limit=100:
     Uncaught AssertionError: expected { Object (error) } to have a property 'features'
      at Test.<anonymous> (test/tables.js:156:32)
      at Test.assert (node_modules/supertest/lib/test.js:156:6)
      at assert (node_modules/supertest/lib/test.js:127:12)
      at node_modules/supertest/lib/test.js:124:5
      at Test.Request.callback (node_modules/supertest/node_modules/superagent/lib/node/index.js:785:12)
      at IncomingMessage.<anonymous> (node_modules/supertest/node_modules/superagent/lib/node/index.js:990:12)
      at _stream_readable.js:944:16

  9) Tables Queries a specific table endoint to get geojson:  Offset = 1000, returnFields set to country and id, limit=100:
     Uncaught AssertionError: expected { Object (error) } to have a property 'features'
      at Test.<anonymous> (test/tables.js:171:32)
      at Test.assert (node_modules/supertest/lib/test.js:156:6)
      at assert (node_modules/supertest/lib/test.js:127:12)
      at node_modules/supertest/lib/test.js:124:5
      at Test.Request.callback (node_modules/supertest/node_modules/superagent/lib/node/index.js:785:12)
      at IncomingMessage.<anonymous> (node_modules/supertest/node_modules/superagent/lib/node/index.js:990:12)
      at _stream_readable.js:944:16

  10) Tables Queries a specific table endoint as csv: whereClause is 1=1, returnFields set to country, limit 100:
     Error: expected "Content-Type" of "text/csv", got "application/json"
      at Test._assertHeader (node_modules/supertest/lib/test.js:215:12)
      at Test._assertFunction (node_modules/supertest/lib/test.js:247:11)
      at Test.assert (node_modules/supertest/lib/test.js:148:18)
      at assert (node_modules/supertest/lib/test.js:127:12)
      at node_modules/supertest/lib/test.js:124:5
      at Test.Request.callback (node_modules/supertest/node_modules/superagent/lib/node/index.js:785:12)
      at IncomingMessage.<anonymous> (node_modules/supertest/node_modules/superagent/lib/node/index.js:990:12)
      at _stream_readable.js:944:16

  11) Tables Queries a specific table endoint as shapefile: whereClause is 1=1, returnFields set to country, limit 100:
     Error: expected "Content-Type" of "application/zip", got "application/json"
      at Test._assertHeader (node_modules/supertest/lib/test.js:215:12)
      at Test._assertFunction (node_modules/supertest/lib/test.js:247:11)
      at Test.assert (node_modules/supertest/lib/test.js:148:18)
      at assert (node_modules/supertest/lib/test.js:127:12)
      at node_modules/supertest/lib/test.js:124:5
      at Test.Request.callback (node_modules/supertest/node_modules/superagent/lib/node/index.js:785:12)
      at IncomingMessage.<anonymous> (node_modules/supertest/node_modules/superagent/lib/node/index.js:990:12)
      at _stream_readable.js:944:16

  12) Vector Tiles requests a dynamic .pbf tile from a PostGIS database:
     Error: expected 200 "OK", got 404 "Not Found"
      at Test._assertStatus (node_modules/supertest/lib/test.js:232:12)
      at Test._assertFunction (node_modules/supertest/lib/test.js:247:11)
      at Test.assert (node_modules/supertest/lib/test.js:148:18)
      at assert (node_modules/supertest/lib/test.js:127:12)
      at node_modules/supertest/lib/test.js:124:5
      at Test.Request.callback (node_modules/supertest/node_modules/superagent/lib/node/index.js:797:3)
      at IncomingMessage.<anonymous> (node_modules/supertest/node_modules/superagent/lib/node/index.js:990:12)
      at _stream_readable.js:944:16
```

**Comment by apollolm** [comment]
The tests that are failing were written against a specific instance and database that I was working with at the time.  I would expect them to fail if that particular database is not being hit.  My efforts to refactor the codebase and create better tests were to address this problem specifically, but remain incomplete.

**Comment by rtodea** [comment]
OK. Thanks for clearing things up!
